insert into user_car_data (id, make, model, price) values (1, 'Volvo', 'S80', '$16714.91');
insert into user_car_data (id, make, model, price) values (2, 'Chevrolet', '2500', '$21322.66');
insert into user_car_data (id, make, model, price) values (3, 'Ford', 'E250', '$26103.94');
insert into user_car_data (id, make, model, price) values (4, 'GMC', 'Vandura G1500', '$26409.95');
insert into user_car_data (id, make, model, price) values (5, 'Cadillac', 'Seville', '$12811.80');
insert into user_car_data (id, make, model, price) values (6, 'Dodge', 'Ram 2500', '$23708.84');
insert into user_car_data (id, make, model, price) values (7, 'Buick', 'Electra', '$25169.74');
insert into user_car_data (id, make, model, price) values (8, 'Infiniti', 'I', '$20742.31');
insert into user_car_data (id, make, model, price) values (9, 'Dodge', 'Avenger', '$17969.38');
insert into user_car_data (id, make, model, price) values (10, 'Plymouth', 'Colt Vista', '$12378.05');
insert into user_car_data (id, make, model, price) values (11, 'Jeep', 'Grand Cherokee', '$13103.16');
insert into user_car_data (id, make, model, price) values (12, 'GMC', 'Sonoma Club Coupe', '$24737.97');
insert into user_car_data (id, make, model, price) values (13, 'Cadillac', 'STS', '$20358.35');
insert into user_car_data (id, make, model, price) values (14, 'Honda', 'Accord', '$14360.88');
insert into user_car_data (id, make, model, price) values (15, 'Dodge', 'Durango', '$17035.40');
insert into user_car_data (id, make, model, price) values (16, 'Porsche', '911', '$25929.03');
insert into user_car_data (id, make, model, price) values (17, 'Land Rover', 'Discovery', '$24264.59');
insert into user_car_data (id, make, model, price) values (18, 'Pontiac', 'Bonneville', '$10870.38');
insert into user_car_data (id, make, model, price) values (19, 'BMW', '325', '$28129.00');
insert into user_car_data (id, make, model, price) values (20, 'Chrysler', 'Sebring', '$15172.66');
insert into user_car_data (id, make, model, price) values (21, 'Pontiac', 'Parisienne', '$29835.98');
insert into user_car_data (id, make, model, price) values (22, 'Mazda', 'Tribute', '$24340.20');
insert into user_car_data (id, make, model, price) values (23, 'Lotus', 'Esprit', '$28871.29');
insert into user_car_data (id, make, model, price) values (24, 'Nissan', 'Pathfinder', '$22607.71');
insert into user_car_data (id, make, model, price) values (25, 'Suzuki', 'Swift', '$21539.15');
insert into user_car_data (id, make, model, price) values (26, 'Mazda', '626', '$29426.57');
insert into user_car_data (id, make, model, price) values (27, 'GMC', 'Envoy XL', '$24954.06');
insert into user_car_data (id, make, model, price) values (28, 'Saturn', 'Ion', '$24871.30');
insert into user_car_data (id, make, model, price) values (29, 'Audi', 'Allroad', '$22270.77');
insert into user_car_data (id, make, model, price) values (30, 'Toyota', 'Avalon', '$24549.17');
insert into user_car_data (id, make, model, price) values (31, 'GMC', 'Savana 2500', '$29169.64');
insert into user_car_data (id, make, model, price) values (32, 'Ford', 'Escort', '$25975.48');
insert into user_car_data (id, make, model, price) values (33, 'Volkswagen', 'Beetle', '$21833.20');
insert into user_car_data (id, make, model, price) values (34, 'Mercedes-Benz', 'CLK-Class', '$29345.01');
insert into user_car_data (id, make, model, price) values (35, 'Buick', 'Skyhawk', '$22903.94');
insert into user_car_data (id, make, model, price) values (36, 'Audi', 'Cabriolet', '$18414.01');
insert into user_car_data (id, make, model, price) values (37, 'GMC', '1500', '$12237.30');
insert into user_car_data (id, make, model, price) values (38, 'Holden', 'VS Commodore', '$15653.52');
insert into user_car_data (id, make, model, price) values (39, 'Lexus', 'CT', '$13409.01');
insert into user_car_data (id, make, model, price) values (40, 'Aston Martin', 'Vanquish S', '$21358.27');
insert into user_car_data (id, make, model, price) values (41, 'Toyota', 'Prius', '$12243.80');
insert into user_car_data (id, make, model, price) values (42, 'Volvo', 'S60', '$20407.12');
insert into user_car_data (id, make, model, price) values (43, 'Mitsubishi', 'Lancer', '$26953.28');
insert into user_car_data (id, make, model, price) values (44, 'Suzuki', 'Grand Vitara', '$13602.06');
insert into user_car_data (id, make, model, price) values (45, 'Pontiac', 'Grand Prix', '$23638.85');
insert into user_car_data (id, make, model, price) values (46, 'Infiniti', 'M', '$17963.11');
insert into user_car_data (id, make, model, price) values (47, 'Ford', 'Escort', '$25210.40');
insert into user_car_data (id, make, model, price) values (48, 'Honda', 'Odyssey', '$24915.76');
insert into user_car_data (id, make, model, price) values (49, 'Cadillac', 'Escalade ESV', '$26763.33');
insert into user_car_data (id, make, model, price) values (50, 'Chevrolet', 'Suburban 1500', '$22775.03');
insert into user_car_data (id, make, model, price) values (51, 'Lexus', 'GS', '$15046.29');
insert into user_car_data (id, make, model, price) values (52, 'Subaru', 'Legacy', '$22109.88');
insert into user_car_data (id, make, model, price) values (53, 'Toyota', 'FJ Cruiser', '$24262.03');
insert into user_car_data (id, make, model, price) values (54, 'Aston Martin', 'Vantage', '$29130.09');
insert into user_car_data (id, make, model, price) values (55, 'Mazda', 'Millenia', '$18845.16');
insert into user_car_data (id, make, model, price) values (56, 'Pontiac', 'Fiero', '$28459.23');
insert into user_car_data (id, make, model, price) values (57, 'Land Rover', 'LR3', '$22258.08');
insert into user_car_data (id, make, model, price) values (58, 'Chevrolet', 'Sportvan G20', '$11726.08');
insert into user_car_data (id, make, model, price) values (59, 'Oldsmobile', '98', '$13316.73');
insert into user_car_data (id, make, model, price) values (60, 'Dodge', 'Ram Van 1500', '$21459.53');
insert into user_car_data (id, make, model, price) values (61, 'Buick', 'Park Avenue', '$25190.38');
insert into user_car_data (id, make, model, price) values (62, 'Lincoln', 'MKZ', '$17710.03');
insert into user_car_data (id, make, model, price) values (63, 'Suzuki', 'Grand Vitara', '$26889.62');
insert into user_car_data (id, make, model, price) values (64, 'Cadillac', 'STS', '$24008.40');
insert into user_car_data (id, make, model, price) values (65, 'BMW', 'X6 M', '$10994.85');
insert into user_car_data (id, make, model, price) values (66, 'Volvo', 'C70', '$21877.90');
insert into user_car_data (id, make, model, price) values (67, 'Ford', 'Mustang', '$28831.65');
insert into user_car_data (id, make, model, price) values (68, 'Pontiac', 'Grand Prix', '$27173.17');
insert into user_car_data (id, make, model, price) values (69, 'Ford', 'Ranger', '$17527.26');
insert into user_car_data (id, make, model, price) values (70, 'BMW', '3 Series', '$15363.64');
insert into user_car_data (id, make, model, price) values (71, 'Mazda', 'B-Series Plus', '$17369.58');
insert into user_car_data (id, make, model, price) values (72, 'Mazda', 'B-Series Plus', '$12991.03');
insert into user_car_data (id, make, model, price) values (73, 'Volkswagen', 'Passat', '$16919.05');
insert into user_car_data (id, make, model, price) values (74, 'Audi', 'S6', '$28168.58');
insert into user_car_data (id, make, model, price) values (75, 'Chevrolet', '2500', '$24547.08');
insert into user_car_data (id, make, model, price) values (76, 'Subaru', 'Impreza', '$26404.84');
insert into user_car_data (id, make, model, price) values (77, 'Suzuki', 'XL-7', '$22284.74');
insert into user_car_data (id, make, model, price) values (78, 'Cadillac', 'Escalade', '$19521.08');
insert into user_car_data (id, make, model, price) values (79, 'GMC', 'Yukon', '$14185.01');
insert into user_car_data (id, make, model, price) values (80, 'Mercedes-Benz', '500E', '$27192.66');
insert into user_car_data (id, make, model, price) values (81, 'Mazda', 'Tribute', '$28399.10');
insert into user_car_data (id, make, model, price) values (82, 'Cadillac', 'Seville', '$22193.29');
insert into user_car_data (id, make, model, price) values (83, 'MINI', 'Cooper', '$27584.99');
insert into user_car_data (id, make, model, price) values (84, 'Ford', 'Explorer Sport Trac', '$29407.96');
insert into user_car_data (id, make, model, price) values (85, 'Oldsmobile', 'Cutlass Cruiser', '$28524.51');
insert into user_car_data (id, make, model, price) values (86, 'Cadillac', 'XLR-V', '$16621.65');
insert into user_car_data (id, make, model, price) values (87, 'Mitsubishi', 'Diamante', '$10662.88');
insert into user_car_data (id, make, model, price) values (88, 'Dodge', 'Spirit', '$27415.45');
insert into user_car_data (id, make, model, price) values (89, 'Chevrolet', 'Monte Carlo', '$18836.05');
insert into user_car_data (id, make, model, price) values (90, 'Mitsubishi', 'Starion', '$11463.12');
insert into user_car_data (id, make, model, price) values (91, 'Chevrolet', 'Impala', '$15055.81');
insert into user_car_data (id, make, model, price) values (92, 'Mercedes-Benz', 'S-Class', '$10534.23');
insert into user_car_data (id, make, model, price) values (93, 'Cadillac', 'Escalade EXT', '$15893.77');
insert into user_car_data (id, make, model, price) values (94, 'Lincoln', 'Continental', '$17177.06');
insert into user_car_data (id, make, model, price) values (95, 'Chevrolet', 'Suburban 2500', '$23288.85');
insert into user_car_data (id, make, model, price) values (96, 'Lotus', 'Esprit', '$16240.94');
insert into user_car_data (id, make, model, price) values (97, 'Toyota', 'Echo', '$17012.10');
insert into user_car_data (id, make, model, price) values (98, 'Buick', 'Regal', '$18242.68');
insert into user_car_data (id, make, model, price) values (99, 'Ford', 'LTD Crown Victoria', '$26906.78');
insert into user_car_data (id, make, model, price) values (100, 'Mitsubishi', 'GTO', '$14139.91');
